<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FFMpegCore" Version="5.5.0" />
    <PackageReference Include="SharpHook" Version="7.1.3" />
  </ItemGroup>

  <ItemGroup Condition="'$(GodotTargetPlatform)' == 'windows' Or ('$(GodotTargetPlatform)' == '' And $([MSBuild]::IsOSPlatform('Windows')))">
    <None Include="$(MSBuildThisFileDirectory)addons/ffmpeg/bin/ffmpeg.exe" Condition="Exists('$(MSBuildThisFileDirectory)addons/ffmpeg/bin/ffmpeg.exe')" CopyToOutputDirectory="PreserveNewest" Link="addons\ffmpeg\bin\ffmpeg.exe" />
  </ItemGroup>
  <ItemGroup Condition="'$(GodotTargetPlatform)' == 'linux' Or ('$(GodotTargetPlatform)' == '' And $([MSBuild]::IsOSPlatform('Linux')))">
    <None Include="$(MSBuildThisFileDirectory)addons/ffmpeg/bin/ffmpeg" Condition="Exists('$(MSBuildThisFileDirectory)addons/ffmpeg/bin/ffmpeg')" CopyToOutputDirectory="PreserveNewest" Link="addons\ffmpeg\bin\ffmpeg" />
  </ItemGroup>
</Project>
